// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV2tu5iWyP3hwGUXZj1JsvOQ5MqiXXblU',
    appId: '1:457407888829:web:fed082bce93067da38e6d4',
    messagingSenderId: '457407888829',
    projectId: 'app-aluno-e02a8',
    authDomain: 'app-aluno-e02a8.firebaseapp.com',
    storageBucket: 'app-aluno-e02a8.firebasestorage.app',
    measurementId: 'G-S6CQ5871VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMa6YvVXptsDq70GJTBuDlU2C-e08OiiM',
    appId: '1:773484977371:android:0da476e1e5e3187d3140fe',
    messagingSenderId: '773484977371',
    projectId: 'prjaula11',
    storageBucket: 'prjaula11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI5vusO7B8m3erBFjynVJ-_5e1AaB1Asg',
    appId: '1:457407888829:ios:7d6314e799dd570038e6d4',
    messagingSenderId: '457407888829',
    projectId: 'app-aluno-e02a8',
    storageBucket: 'app-aluno-e02a8.firebasestorage.app',
    iosBundleId: 'com.example.appAluno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI5vusO7B8m3erBFjynVJ-_5e1AaB1Asg',
    appId: '1:457407888829:ios:7d6314e799dd570038e6d4',
    messagingSenderId: '457407888829',
    projectId: 'app-aluno-e02a8',
    storageBucket: 'app-aluno-e02a8.firebasestorage.app',
    iosBundleId: 'com.example.appAluno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV2tu5iWyP3hwGUXZj1JsvOQ5MqiXXblU',
    appId: '1:457407888829:web:3da353352d6a0c1838e6d4',
    messagingSenderId: '457407888829',
    projectId: 'app-aluno-e02a8',
    authDomain: 'app-aluno-e02a8.firebaseapp.com',
    storageBucket: 'app-aluno-e02a8.firebasestorage.app',
    measurementId: 'G-L65TQZZJ97',
  );
}