// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFBTOaMxwITKGx4PPGaUuXcoCrRtxjTok',
    appId: '1:773484977371:web:b966f81f5f8b000a3140fe',
    messagingSenderId: '773484977371',
    projectId: 'prjaula11',
    authDomain: 'prjaula11.firebaseapp.com',
    storageBucket: 'prjaula11.firebasestorage.app',
    measurementId: 'G-N7MG435T2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMa6YvVXptsDq70GJTBuDlU2C-e08OiiM',
    appId: '1:773484977371:android:0da476e1e5e3187d3140fe',
    messagingSenderId: '773484977371',
    projectId: 'prjaula11',
    storageBucket: 'prjaula11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb-IKOejFIBq6RjLORu6RRstx_7aYF5F8',
    appId: '1:773484977371:ios:e6c059cc5a5907563140fe',
    messagingSenderId: '773484977371',
    projectId: 'prjaula11',
    storageBucket: 'prjaula11.firebasestorage.app',
    iosBundleId: 'com.example.appAluno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb-IKOejFIBq6RjLORu6RRstx_7aYF5F8',
    appId: '1:773484977371:ios:e6c059cc5a5907563140fe',
    messagingSenderId: '773484977371',
    projectId: 'prjaula11',
    storageBucket: 'prjaula11.firebasestorage.app',
    iosBundleId: 'com.example.appAluno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFBTOaMxwITKGx4PPGaUuXcoCrRtxjTok',
    appId: '1:773484977371:web:25a593c1a83cfe0b3140fe',
    messagingSenderId: '773484977371',
    projectId: 'prjaula11',
    authDomain: 'prjaula11.firebaseapp.com',
    storageBucket: 'prjaula11.firebasestorage.app',
    measurementId: 'G-HRR3J35KN7',
  );
}
